# Generated by Django 5.2 on 2025-04-10 11:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('platform_title', models.CharField(default='Эксперт платформы "SOULHAVEN"', max_length=255)),
                ('profile_image', models.ImageField(upload_to='experts/profile_images/')),
                ('education', models.TextField()),
                ('specialization', models.TextField()),
                ('experience', models.IntegerField()),
                ('methods', models.TextField(help_text='Описание методов работы')),
                ('tools', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Список инструментов работы', size=None)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='experts/certificates/')),
                ('certificate_text', models.TextField(blank=True)),
                ('personal_message', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
