# Generated by Django 5.2 on 2025-04-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_header', models.CharField(max_length=255)),
                ('paragraph1', models.TextField()),
                ('header2', models.CharField(max_length=255)),
                ('paragraph2', models.TextField()),
                ('header3', models.CharField(max_length=255)),
                ('paragraph3', models.TextField()),
                ('themes', models.CharField(help_text='Comma-separated list of themes', max_length=255)),
                ('footer_note', models.TextField(blank=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
